apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: hq
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "*"
  DefaultAllowPrivilegeEscalation: false
  allowPrivilegeEscalation: false
