apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-nginx1
  annotations:
    ingress.kubernetes.io/connection-proxy-header: keep-alive
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ubuhq1
    http:
      paths:
      - backend:
          serviceName: ing-nginx
          servicePort: 80
        path: /s1
