apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: clustern
spec:
  hubAcceptsClient: false
  leaseDurationSeconds: 60
  taints:
    - key: gpu
      value: "true"
      effect: "NoSelect"
