apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: localtime-all
spec:
  volumeMounts:
    - mountPath: /etc/localtime
      name: localtime
      readOnly: true
  volumes:
    - name: localtime
      hostPath:
        path: /etc/localtime
