apiVersion: v1
kind: Service
metadata:
  name: sts-nginx
  labels:
    app: sts-nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: sts-nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "sts-nginx"
  replicas: 1
  selector:
    matchLabels:
      app: sts-nginx
  template:
    metadata:
      labels:
        app: sts-nginx
    spec:
      containers:
      - name: sts-nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: pvc-local
          mountPath: /usr/share/nginx/html
      volumes:
        - name: pvc-local
          hostPath:
            path: /opt/mjli
            type: Directory
