apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
  admissionChecks:
  - sample-multikueue
  - ocm-multikueue
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue"
spec:
  clusterQueue: "cluster-queue"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: AdmissionCheck
metadata:
  name: sample-multikueue
spec:
  controllerName: kueue.x-k8s.io/multikueue
  parameters:
    apiGroup: kueue.x-k8s.io
    kind: MultiKueueConfig
    name: ocm-multikueue
---
# This controller will read placement nvidia-t4 and generate corresponding MultiKueueConfig, MultiKueueCluster.
apiVersion: kueue.x-k8s.io/v1beta1
kind: AdmissionCheck
metadata:
  name: ocm-multikueue
spec:
  controllerName: open-cluster-management.io/placement
  parameters:
    apiGroup: cluster.open-cluster-management.io
    kind: Placement
    name: nvidia-t4
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nvidia-t4
  namespace: kueue-system
spec:
  clusterSets:
  - spoke
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
#---
#The below resource will be generated by controller open-cluster-management.io/placement.
#apiVersion: kueue.x-k8s.io/v1alpha1
#kind: MultiKueueConfig
#metadata:
#  name: multikueue-test
#spec:
#  clusters:
#  - multikueue-test-worker1
#  - multikueue-test-worker2
#---
#apiVersion: kueue.x-k8s.io/v1alpha1
#kind: MultiKueueCluster
#metadata:
#  name: multikueue-test-worker1
#spec:
#  kubeConfig:
#    locationType: Secret
#    location: multikueue-ocm-sa-cluster1-kubeconfig
#    # a secret called "worker1-secret" should be created in the namespace the kueue
#    # controller manager runs into, holding the kubeConfig needed to connect to the
#    # worker cluster in the "kubeconfig" key;
#---
#apiVersion: kueue.x-k8s.io/v1alpha1
#kind: MultiKueueCluster
#metadata:
#  name: multikueue-test-worker2
#spec:
#  kubeConfig:
#    locationType: Secret
#    location: multikueue-ocm-sa-cluster2-kubeconfig