apiVersion: v1
kind: Service
metadata:
  name: nginx-local
spec:
  selector:
    app: nginx-local
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-local
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-local
    spec:
      containers:
      - name: nginx
        image: siji/nginx:1.12.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/html"
          name: nginx-data
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: pvc-local
