apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
   - name: nginx
     image: siji/nginx:1.12.2
     ports:
     - containerPort: 80
     volumeMounts:
     - mountPath: "/var/www/html"
       name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory
