apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: helloworld
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
spec:
  addOnMeta:
    description: helloworld is an example addon created by go template
    displayName: helloworld
  installStrategy:
    type: Placements
    placements:
    - name: placement-all
      namespace: default
      configs:
      - group: addon.open-cluster-management.io
        resource: addonhubconfigs
        name: config-v3
      rolloutStrategy:
        type: Progressive
        progressive:
          mandatoryDecisionGroups:
          - prod-canary-west
          - prod-canary-east
          maxConcurrency: 50%
          timeout: 0
