apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: managed-serviceaccount
  annotations:
    addon.open-cluster-management.io/lifecycle: addon-manager
    meta.helm.sh/release-name: managed-serviceaccount
    meta.helm.sh/release-namespace: open-cluster-management-addon
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  addOnMeta:
    description: managed-serviceaccount
    displayName: managed-serviceaccount
  installStrategy:
    placements:
    - name: placement-all
      namespace: default
      rolloutStrategy:
        type: Progressive
        progressive:
          mandatoryDecisionGroups:
          - groupName: "canary"
          maxConcurrency: 1
    type: Placements
  supportedConfigs:
  - defaultConfig:
      name: managed-serviceaccount-0.6.2
    group: addon.open-cluster-management.io
    resource: addontemplates
