apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: config-v2
  namespace: open-cluster-management
spec:
  customizedVariables:
    - name: k2
      value: v2
