apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: config-v1
  namespace: open-cluster-management
spec:
  customizedVariables:
    - name: k1
      value: v1