#  clusteradm clusterset bind global --namespace default
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-canary
  namespace: default
spec:
  numberOfClusters: 1
  clusterSets:
    - global