#  clusteradm clusterset bind global --namespace default
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-all
  namespace: default
spec:
  clusterSets:
    - global
#  tolerations:
#    - key: "cluster.open-cluster-management.io/unreachable"
#      operator: Exists
