apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement5
  namespace: ns1
spec:
  predicates:
    - requiredClusterSelector:
        claimSelector:
          matchExpressions:
            - key: platform.open-cluster-management.io
              operator: In
              values:
                - aws
