apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
 name: hq-spoke
 namespace: server-foundation
 annotations:
   cluster.open-cluster-management.io/createmanagedcluster: "false"
spec:
 clusterPoolName: server-foundation-ocp-10-20
 subjects:
 - apiGroup: rbac.authorization.k8s.io
   kind: Group
   name: Server Foundation
