apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
 name: hq-spoke
 namespace: server-foundation
 annotations:
   cluster.open-cluster-management.io/createmanagedcluster: "false"
 labels:
   do-not-hibernate: "true"
spec:
 clusterPoolName: sf-prow-aws-ocp414-sno-us-east-2
 subjects:
 - apiGroup: rbac.authorization.k8s.io
   kind: Group
   name: Server Foundation
