apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
 name: qhao
 namespace: acm-observability-china
 labels:
   do-not-delete: "true"
spec:
 clusterPoolName: obs-china-aws-4616
 subjects:
 - apiGroup: rbac.authorization.k8s.io
   kind: Group
   name: Core-Services
