apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
 name: qhao
 namespace: server-foundation
spec:
 clusterPoolName: server-foundation-aws
 subjects:
 - apiGroup: rbac.authorization.k8s.io
   kind: Group
   name: Server Foundation
