allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: glusterfs3
parameters:
  resturl: https://10.0.29.66:8080
  restuser: admin
  secretName: heketi-secret
  secretNamespace: kube-system
  volumenameprefix: icp
  volumeType: replicate:3
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
