apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: demo2
spec:
  numberOfClusters: 1
  prioritizerPolicy:
    mode: Exact
    configurations:
      - scoreCoordinate:
          type: AddOn
          addOn:
            resourceName: demo2
            scoreName: customized
        weight: 1
