apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: demo1-1
spec:
  numberOfClusters: 2
  prioritizerPolicy:
    mode: Exact
    configurations:
      - scoreCoordinate:
          type: AddOn
          addOn:
            resourceName: demo1
            scoreName: cpuratio
        weight: 1
