apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: demo1-2
spec:
  numberOfClusters: 2
  prioritizerPolicy:
    mode: Exact
    configurations:
      - scoreCoordinate:
          type: BuiltIn
          builtIn: Steady
        weight: 3
      - scoreCoordinate:
          type: AddOn
          addOn:
            resourceName: demo1
            scoreName: cpuratio
        weight: 1
