apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement2
spec:
  numberOfClusters: 1
  tolerations:
    - key: "unavailable"
      operator: Exists
      tolerationSeconds: 30
