apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: placement1
  namespace: default
spec:
  numberOfClusters: 3
  clusterSets:
    - prod
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            purpose: test
  polices:
    - type: 0
      weight: 1000
  resourceWeights:
    - type: 0
      weight: 100
    - type: 1
      weight: 200
