apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv2-hostpath
    labels:
      type: hostpath
spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /hostpath/pv2
