apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "demo.name" . }}
    helm.sh/chart: {{ include "demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    description: Defines how to create glusterfs storage class
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: {{ include "demo.fullname" . }}
      labels:
        app.kubernetes.io/name: {{ include "demo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/sc/storage_class.sh"]
          volumeMounts:
            - name: storage-class
              mountPath: "/sc"
      volumes:
        - name: storage-class
          configMap:
            name: {{ include "demo.fullname" . }}
            defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
