apiVersion: v1
kind: Service
metadata:
  labels:
    run: ing-nginx
  name: ing-nginx
spec:
  ports:
  - name: nginx
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: ing-nginx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ing-nginx
  name: ing-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      run: ing-nginx
  template:
    metadata:
      labels:
        run: ing-nginx
    spec:
      containers:
      - image: haoqing/web-socket-example
        imagePullPolicy: IfNotPresent
        name: ing-nginx
        args:
        - python
        - /tmp/tornado-websocket-example/app.py
        ports:
        - containerPort: 8888
          protocol: TCP
