apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-ws
spec:
  rules:
  - host: ubuhq6.eng.platformlab.ibm.com
    http:
      paths:
      - backend:
          serviceName: ing-ws
          servicePort: 8888
