---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSet
metadata:
  name: hq
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSetBinding
metadata:
  name: hq
  namespace: demo
spec:
  clusterSet: hq
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: cluster2
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: cluster3
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: cluster4
#---
#apiVersion: cluster.open-cluster-management.io/v1
#kind: ManagedCluster
#metadata:
#  name: cluster2
#  labels:
#    cluster.open-cluster-management.io/clusterset: hq
#spec:
#  hubAcceptsClient: false
#---
#apiVersion: cluster.open-cluster-management.io/v1
#kind: ManagedCluster
#metadata:
#  name: cluster3
#  labels:
#    cluster.open-cluster-management.io/clusterset: hq
#spec:
#  hubAcceptsClient: false
#---
#apiVersion: cluster.open-cluster-management.io/v1
#kind: ManagedCluster
#metadata:
#  name: cluster4
#  labels:
#    cluster.open-cluster-management.io/clusterset: hq
#spec:
#  hubAcceptsClient: false
