apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: placement1
spec:
  numberOfClusters: 1
  prioritizerPolicy:
    configurations:
      - name: CustomizeResourceAllocatableMemory
