---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: podinfo-allow-quayio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: dockerhub
        image: quay.io/crio/nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
