---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: podinfo-va-faild
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfod
        image: mycluster.icp:8500/default/nginx:1.13.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
