apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: demo1
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: purpose
              operator: In
#              values:
#                - test
  tolerations:
    - key: "cluster.open-cluster-management.io/unreachable"
      operator: Exists
  prioritizerPolicy:
    mode: Exact
    configurations:
      - scoreCoordinate:
          type: BuiltIn
          builtIn: Steadyy
        weight: 3
